heat_template_version: 2015-10-15

parameters:
  image:
    type: string
    default: cirros-0.3.5-x86_64-disk

  flavor:
    type: string
    default: m1.nano

  net:
    type: string
    default: private

resources:

  handle:
    type: OS::Heat::WaitConditionHandle
  waiter:
    type: OS::Heat::WaitCondition
    depends_on: server
    properties:
      timeout: 120
      handle: { get_resource: handle }
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: {get_param: net}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh -x
            WC_NOTIFY -k -d '{"status": "SUCCESS", "reason": "ready!", "data": "done", "id": "server1"}'
          params:
            WC_NOTIFY: { get_attr: [ handle, curl_cli ] }

outputs:
  networks:
    value: { get_attr: [server, networks ] }
  addresses:
    value: { get_attr: [server, addresses ] }
  ip:
    value: { get_attr: [server, networks, {get_param: net }, 0 ] }
  signal:
    value: { get_attr: [ handle, curl_cli ] }
